from .. import views
from django.urls import path

urlpatterns = [
    path("",                                    views.ContestListView.as_view(),   name="contest_list"),
    path("new/",                                views.ContestFormView.as_view(),   name="contest_create"),
    path("<int:pk>/",                           views.ContestDetailView.as_view(), name="contest_detail"),
    path("<int:pk>/teams/",                     views.ViewTeamsView.as_view(),     name="contest_teams"),
    path("<int:pk>/jurys/",                     views.ViewJurysView.as_view(),     name="contest_jurys"),
    path("<int:pk>/leaderboard/",                views.ContestLeaderboardView.as_view(), name="contest_leaderboard"),
    path("<int:pk>/leaderboard/api/",            views.LeaderboardAPIView.as_view(), name="contest_leaderboard_api"),
    path("<int:pk>/leaderboard/admin/",          views.AdminLeaderboardDashboardView.as_view(), name="admin_leaderboard_dashboard"),
    path("<int:pk>/leaderboard/finish/",         views.AdminFinishEvaluationView.as_view(), name="admin_finish_evaluation"),
    path("<int:pk>/leaderboard/jury-toggle/",    views.AdminToggleJuryBreakdownView.as_view(), name="admin_toggle_jury_breakdown"),
    path("<int:pk>/leaderboard/recalculate/",    views.AdminRecalculateLeaderboardView.as_view(), name="admin_recalculate_leaderboard"),
    path("<int:pk>/leaderboard/export/",         views.AdminExportLeaderboardView.as_view(), name="admin_export_leaderboard"),
    path("<int:pk>/leaderboard/team/<int:team_pk>/", views.TeamDetailLeaderboardView.as_view(), name="team_leaderboard_detail"),
    path("<int:pk>/teams/<int:ck>/",            views.TeamDetailView.as_view(),    name="team_detail"),
    path("<int:pk>/teams/<int:ck>/kick/<int:user_id>/",     views.TeamKickView.as_view(),      name="team_kick"),
    path("<int:pk>/teams/<int:ck>/block/<int:user_id>/",    views.TeamBlockView.as_view(),     name="team_block"),
    path("<int:pk>/teams/<int:ck>/unblock/<int:user_id>/",  views.TeamUnblockView.as_view(),   name="team_unblock"),
    path("<int:pk>/edit/",                      views.ContestFormView.as_view(),   name="contest_edit"),
    path("<int:pk>/delete/",                    views.ContestDeleteView.as_view(), name="contest_delete"),
    path("<int:pk>/apply/<str:app_type>/",      views.ApplyToContestView.as_view(),name="apply_to_contest"),
    path("<int:pk>/rounds/",                    views.RoundListView.as_view(),     name="contest_rounds"),
    path("<int:pk>/rounds/new/",                views.RoundCreateView.as_view(),   name="round_create"),
    path("<int:pk>/rounds/<int:round_id>/edit/",       views.RoundEditView.as_view(),     name="round_edit"),
    path("<int:pk>/rounds/<int:round_id>/activate/",   views.RoundActivateView.as_view(), name="round_activate"),
    path("<int:pk>/rounds/<int:round_id>/close/",      views.RoundCloseSubmissionsView.as_view(), name="round_close_submissions"),
    path("<int:pk>/rounds/<int:round_id>/extend/",     views.RoundExtendDeadlineView.as_view(), name="round_extend_deadline"),
    path("<int:pk>/rounds/team/",               views.ContestRoundsTeamView.as_view(), name="contest_rounds_team"),
    path("<int:pk>/rounds/<int:round_id>/team/", views.RoundDetailTeamView.as_view(), name="round_detail_team"),
]
