# Generated by Django 6.0.2 on 2026-02-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ORGANIZER', 'Organizer'), ('JUDGE', 'Judge'), ('PARTICIPANT', 'Participant')], default='PARTICIPANT', max_length=20),
        ),
    ]
