# Generated by Django 6.0.2 on 2026-02-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contest_jury_contest_organizer_contest_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'Organizer'), ('JURY', 'Jury'), ('PARTICIPANT', 'Participant')], default='PARTICIPANT', max_length=20),
        ),
    ]
