# Generated by Django 6.0.1 on 2026-02-23 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='jury',
            new_name='jurys',
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('JURY', 'Jury'), ('PARTICIPANT', 'Participant')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_apps', to='app.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'contest', 'application_type')},
            },
        ),
    ]
