# Generated by Django 6.0.1 on 2026-02-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_jury_contest_jurys_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REGISTRATION', 'Registration'), ('RUNNING', 'Running'), ('FINISHED', 'Finished')], default='DRAFT', max_length=20),
        ),
    ]
