# Generated by Django 6.0.2 on 2026-02-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_contest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('JURY', 'Jury'), ('PARTICIPANT', 'Participant')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REGISTRATION', 'Registration'), ('RUNNING', 'Running'), ('FINISHED', 'Finished')], default='DRAFT'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'Organizer'), ('JURY', 'Jury'), ('PARTICIPANT', 'Participant')], default='PARTICIPANT'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
