# Generated by Django 6.0.2 on 2026-03-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_application_application_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
