# Generated by Django 6.0.2 on 2026-03-01 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_contest_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('JURY', 'Jury'), ('TEAM', 'Team'), ('PARTICIPANT', 'Participant')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_apps', to='app.contest'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active')], default='DRAFT')),
                ('participants', models.ManyToManyField(related_name='participated_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_apps', to='app.team'),
        ),
    ]
