# Generated by Django 6.0.2 on 2026-03-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_application_application_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teams_in_contests', to='app.team'),
        ),
    ]
