# Generated by Django 6.0.2 on 2026-03-25 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='blacklisted_members',
            field=models.ManyToManyField(blank=True, related_name='blacklisted_from_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captained_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
