# Generated by Django 6.0.3 on 2026-04-07 15:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_team_blacklisted_members_team_captain"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContestEvaluationPhase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("NOT_STARTED", "Not started"), ("IN_PROGRESS", "In progress"), ("COMPLETED", "Completed")], default="NOT_STARTED", max_length=20)),
                ("trigger_type", models.CharField(choices=[("AUTO", "Automatic"), ("MANUAL", "Manual")], default="AUTO", max_length=10)),
                ("all_scores_complete", models.BooleanField(default=False)),
                ("show_jury_breakdown_to_participants", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("contest", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="evaluation_phase", to="app.contest")),
            ],
        ),
        migrations.CreateModel(
            name="ScoringCriterion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("max_score", models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ("weight", models.DecimalField(decimal_places=2, default=Decimal("1.00"), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("aggregation_type", models.CharField(choices=[("SUM", "Sum"), ("AVERAGE", "Average")], default="AVERAGE", max_length=10)),
                ("order", models.PositiveIntegerField(default=0)),
                ("contest", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="scoring_criteria", to="app.contest")),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("contest", "name")},
            },
        ),
        migrations.CreateModel(
            name="LeaderboardEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rank", models.PositiveIntegerField()),
                ("total_score", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("is_tied", models.BooleanField(default=False)),
                ("category_scores", models.JSONField(blank=True, default=dict)),
                ("jury_breakdown", models.JSONField(blank=True, default=dict)),
                ("missing_scores", models.JSONField(blank=True, default=list)),
                ("computation_complete", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contest", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leaderboard_entries", to="app.contest")),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leaderboard_entries", to="app.team")),
            ],
            options={
                "ordering": ["rank", "-total_score", "team__name"],
                "unique_together": {("contest", "team")},
            },
        ),
        migrations.CreateModel(
            name="JuryScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contest", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="jury_scores", to="app.contest")),
                ("jury_member", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="jury_scores_given", to=settings.AUTH_USER_MODEL)),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="jury_scores", to="app.team")),
                ("criterion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="jury_scores", to="app.scoringcriterion")),
            ],
            options={
                "ordering": ["contest_id", "team_id", "criterion__order", "jury_member_id"],
                "unique_together": {("contest", "team", "jury_member", "criterion")},
            },
        ),
    ]
