# Generated by Django 6.0.1 on 2026-04-05 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_team_blacklisted_members_team_captain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestEvaluationPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=12)),
                ('trigger_type', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual')], default='AUTO', max_length=6)),
                ('all_scores_complete', models.BooleanField(default=False)),
                ('show_jury_breakdown_to_participants', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_phase', to='app.contest')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_score', models.FloatField(default=100)),
                ('weight', models.FloatField(default=1.0)),
                ('aggregation_type', models.CharField(choices=[('SUM', 'Sum'), ('AVERAGE', 'Average')], default='SUM', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_criteria', to='app.contest')),
            ],
            options={
                'ordering': ['contest', 'order', 'name'],
                'unique_together': {('contest', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('is_tied', models.BooleanField(default=False)),
                ('category_scores', models.JSONField(blank=True, default=dict)),
                ('jury_breakdown', models.JSONField(blank=True, default=dict)),
                ('missing_scores', models.JSONField(blank=True, default=list)),
                ('computation_complete', models.BooleanField(default=False)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='app.contest')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='app.team')),
            ],
            options={
                'ordering': ['contest', 'rank', 'team__name'],
                'unique_together': {('contest', 'team')},
            },
        ),
        migrations.CreateModel(
            name='JuryScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_scores', to='app.contest')),
                ('jury_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_given', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_scores', to='app.team')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='app.scoringcriterion')),
            ],
            options={
                'unique_together': {('contest', 'team', 'jury_member', 'criterion')},
            },
        ),
    ]
