# Generated by Django 6.0.1 on 2026-04-05 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_contestevaluationphase_scoringcriterion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech_requirements', models.TextField()),
                ('must_have', models.JSONField(default=list, help_text='List of required checklist items')),
                ('start_time', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('materials', models.JSONField(blank=True, default=list, help_text='List of {label, url}')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUBMISSION_CLOSED', 'Submission Closed'), ('EVALUATED', 'Evaluated')], default='DRAFT', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Round number within contest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='app.contest')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contest', 'order', 'created_at'],
                'unique_together': {('contest', 'order')},
            },
        ),
    ]
