# Generated by Django 6.0.4 on 2026-04-08 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(help_text='Link to GitHub repository')),
                ('video_url', models.URLField(help_text='Link to video demo (YouTube, Drive, etc.)')),
                ('live_demo_url', models.URLField(blank=True, help_text='Link to live demo (optional)')),
                ('description', models.TextField(blank=True, help_text='Short description: what was done, how to run', max_length=2000)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app.team')),
            ],
            options={
                'unique_together': {('round', 'team')},
            },
        ),
    ]
