# Generated by Django 6.0.4 on 2026-04-10 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REGISTRATION_OPEN', 'Registration Open'), ('ROUND_STARTED', 'Round Started'), ('DEADLINE_APPROACHING', 'Deadline Approaching'), ('SUBMISSIONS_CLOSED', 'Submissions Closed'), ('EVALUATION_COMPLETE', 'Evaluation Complete'), ('APPLICATION_UPDATE', 'Application Update'), ('ANNOUNCEMENT', 'Announcement')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='URL to navigate to when clicked', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
