# Generated by Django 6.0.4 on 2026-04-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_announcement_scheduleevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='format',
            field=models.CharField(blank=True, help_text='e.g. Online, Onsite, Hybrid', max_length=50),
        ),
        migrations.AddField(
            model_name='contest',
            name='max_teams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='registration_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='registration_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
