# Generated by Django 6.0.4 on 2026-04-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_contest_format_contest_max_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='discord_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='telegram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='website_link',
            field=models.URLField(blank=True),
        ),
    ]
