# Generated by Django 6.0.4 on 2026-04-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_juryassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juryassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
