# Generated by Django 6.0.4 on 2026-04-25 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_juryassignment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to='app.round'),
        ),
    ]
