# Generated by Django 6.0.4 on 2026-05-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_scheduleevent_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='materials',
            field=models.JSONField(blank=True, default=list, help_text='List of {label, url}', null=True),
        ),
    ]
