# Generated by Django 6.0.4 on 2026-05-10 08:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_round_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('desired_role', models.CharField(choices=[('ORGANIZER', 'Organizer'), ('JURY', 'Jury')], max_length=20, verbose_name='Desired Role')),
                ('reason', models.TextField(verbose_name='Why do you want to join?')),
                ('experience', models.TextField(verbose_name='Relevant experience')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='app.contest', verbose_name='Contest'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Is Pinned'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='format',
            field=models.CharField(blank=True, help_text='e.g. Online, Onsite, Hybrid', max_length=50, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Is Draft'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='max_teams',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Teams'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_contests', to=settings.AUTH_USER_MODEL, verbose_name='Organizer'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='registration_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registration End'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='registration_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Registration Start'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REGISTRATION', 'Registration'), ('RUNNING', 'Running'), ('FINISHED', 'Finished')], default='DRAFT', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='round',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='app.contest', verbose_name='Contest'),
        ),
        migrations.AlterField(
            model_name='round',
            name='deadline',
            field=models.DateTimeField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='round',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='round',
            name='materials',
            field=models.JSONField(blank=True, default=list, help_text='List of {label, url}', null=True, verbose_name='Materials'),
        ),
        migrations.AlterField(
            model_name='round',
            name='must_have',
            field=models.JSONField(default=list, help_text='List of required checklist items', verbose_name='Must-Have Checklist'),
        ),
        migrations.AlterField(
            model_name='round',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Round number within contest', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='round',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUBMISSION_CLOSED', 'Submission Closed'), ('EVALUATED', 'Evaluated')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='round',
            name='tech_requirements',
            field=models.TextField(verbose_name='Technical Requirements'),
        ),
        migrations.AlterField(
            model_name='round',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to='app.contest', verbose_name='Contest'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='event_type',
            field=models.CharField(choices=[('ROUND', 'Round'), ('DEADLINE', 'Deadline'), ('WORKSHOP', 'Workshop'), ('OTHER', 'Other')], default='ROUND', max_length=20, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to='app.round', verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='scoringcriterion',
            name='aggregation_type',
            field=models.CharField(choices=[('SUM', 'Sum'), ('AVERAGE', 'Average')], default='AVERAGE', max_length=10, verbose_name='Aggregation Type'),
        ),
        migrations.AlterField(
            model_name='scoringcriterion',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_criteria', to='app.contest', verbose_name='Contest'),
        ),
        migrations.AlterField(
            model_name='scoringcriterion',
            name='max_score',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max Score'),
        ),
        migrations.AlterField(
            model_name='scoringcriterion',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='scoringcriterion',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='scoringcriterion',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(blank=True, help_text='Short description: what was done, how to run', max_length=2000, verbose_name='Implementation Details'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='github_url',
            field=models.URLField(help_text='Link to GitHub repository', verbose_name='GitHub Repository URL'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='live_demo_url',
            field=models.URLField(blank=True, help_text='Link to live demo (optional)', verbose_name='Live Demo URL'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app.round', verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app.team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='video_url',
            field=models.URLField(help_text='Link to video demo (YouTube, Drive, etc.)', verbose_name='Presentation Video URL'),
        ),
        migrations.AlterField(
            model_name='team',
            name='blacklisted_members',
            field=models.ManyToManyField(blank=True, related_name='blacklisted_from_teams', to=settings.AUTH_USER_MODEL, verbose_name='Blacklisted Members'),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captained_teams', to=settings.AUTH_USER_MODEL, verbose_name='Captain'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='team',
            name='discord_link',
            field=models.URLField(blank=True, verbose_name='Discord Link'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='organization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='team',
            name='participants',
            field=models.ManyToManyField(related_name='participated_teams', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active')], default='DRAFT', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='team',
            name='telegram_link',
            field=models.URLField(blank=True, verbose_name='Telegram Link'),
        ),
        migrations.AlterField(
            model_name='team',
            name='website_link',
            field=models.URLField(blank=True, verbose_name='Website Link'),
        ),
    ]
