from .views_base import (
    ContestContextMixin,
    OrganizerRequiredMixin,
    RedirectToRegisterMixin,
)

from .views_general import HomeView, ProfileView, DashboardView, SettingsView
from .views_contest import ContestDeleteView, ContestDetailView, ContestFormView, ContestListView
from .views_application import ApplicationActionView, ApplyToContestView
from .views_announcement import AnnouncementCreateView, AnnouncementDeleteView, AnnouncementListView
from .views_analytics import (
    OrganizerAnalyticsView,
    RegenerateScheduleView,
    ScheduleEventCreateView,
    ScheduleEventDeleteView,
    ScheduleView,
)
from .views_auth import RegisterView
from .views_leaderboard import (
    AdminExportLeaderboardView,
    AdminFinishEvaluationView,
    AdminLeaderboardDashboardView,
    AdminRecalculateLeaderboardView,
    AdminToggleJuryBreakdownView,
    ContestLeaderboardView,
    ExportEvaluationsCSVView,
    ExportTeamsCSVView,
    LeaderboardAPIView,
    TeamDetailLeaderboardView,
)
from .views_notification import MarkAllReadView, MarkNotificationReadView, NotificationListView
from .views_rounds import (
    ContestRoundsTeamView,
    RoundActivateView,
    RoundCloseSubmissionsView,
    RoundCreateView,
    RoundDetailTeamView,
    RoundDetailView,
    RoundEditView,
    RoundExtendDeadlineView,
    RoundListView,
)
from .views_submission import RoundSubmissionsListView, SubmissionCreateEditView, SubmissionDetailView
from .views_team import (
    AdminPermissionMixin,
    LeaderboardAccessMixin,
    TeamBlockView,
    TeamCreateView,
    TeamDetailView,
    TeamJoinView,
    TeamKickView,
    TeamUnblockView,
    TeamUpdateView,
    ViewJurysView,
    ViewTeamsView,
)

__all__ = [
    "RedirectToRegisterMixin",
    "ContestContextMixin",
    "OrganizerRequiredMixin",
    "HomeView",
    "ProfileView",
    "DashboardView",
    "SettingsView",
    "ContestListView",
    "ContestDetailView",
    "ContestFormView",
    "ContestDeleteView",
    "ApplicationActionView",
    "ApplyToContestView",
    "AnnouncementListView",
    "AnnouncementCreateView",
    "AnnouncementDeleteView",
    "OrganizerAnalyticsView",
    "ScheduleView",
    "ScheduleEventCreateView",
    "ScheduleEventDeleteView",
    "RegenerateScheduleView",
    "ViewTeamsView",
    "ViewJurysView",
    "TeamDetailView",
    "TeamKickView",
    "TeamBlockView",
    "TeamUnblockView",
    "TeamCreateView",
    "TeamUpdateView",
    "TeamJoinView",
    "LeaderboardAccessMixin",
    "AdminPermissionMixin",
    "ContestLeaderboardView",
    "TeamDetailLeaderboardView",
    "LeaderboardAPIView",
    "AdminLeaderboardDashboardView",
    "AdminFinishEvaluationView",
    "AdminToggleJuryBreakdownView",
    "AdminRecalculateLeaderboardView",
    "AdminExportLeaderboardView",
    "ExportEvaluationsCSVView",
    "ExportTeamsCSVView",
    "RoundListView",
    "RoundCreateView",
    "RoundEditView",
    "RoundActivateView",
    "RoundCloseSubmissionsView",
    "RoundExtendDeadlineView",
    "ContestRoundsTeamView",
    "RoundDetailTeamView",
    "RoundDetailView",
    "SubmissionCreateEditView",
    "SubmissionDetailView",
    "RoundSubmissionsListView",
    "RegisterView",
    "NotificationListView",
    "MarkNotificationReadView",
    "MarkAllReadView",
]
